# -*- coding: utf-8 -*-
"""get-electric-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChzsAR856fKzlPXWzRutNZHITe1Q435p
"""

import requests
import pandas as pd

url = "https://data.cityofnewyork.us/resource/jr24-e7cr.json"

data = []
offset = 0

while True:
    r = requests.get(url, params={"$limit": 50000, "$offset": offset})
    batch = r.json()
    if not batch:
        break
    data.extend(batch)
    offset += 50000

df=pd.DataFrame(data)

# Save data as csv
df.to_csv("electric_consumption_raw.csv", index=False)
