# -*- coding: utf-8 -*-
"""get-electric-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChzsAR856fKzlPXWzRutNZHITe1Q435p
"""

#Import required libraries
import requests
import pandas as pd
from google.cloud import storage
from datetime import datetime

#Create variables for use
url = "https://data.cityofnewyork.us/resource/jr24-e7cr.json"
bucket_name="rweaver-electric-consumption-data"
folder_name="electric_consumption/"

data = []
offset = 0

#Create while loop to collect all pages of data from NYC Open Data site via API
while True:
    r = requests.get(url, params={"$limit": 50000, "$offset": offset})
    batch = r.json()
    if not batch:
        break
    data.extend(batch)
    offset += 50000

#Create dataframe with data retrieved
df=pd.DataFrame(data)

#Script to store dataframe in GCS

client=storage.Client()
bucket= client.bucket(bucket_name)
filename=f"electric_consumption_{datetime.now().strftime('%Y%m%d')}.csv"
blob=bucket.blob(filename)

df.to_csv(filename,index=False)
blob.upload_from_filename(filename)
